name: gh-pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /flutter-meme-generator/
          webRenderer: canvaskit
          customArgs: -t lib/main_dev.dart
